# Generated by Django 2.0.7 on 2018-08-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20180814_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
