# Generated by Django 2.0.7 on 2018-08-14 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala', '0002_auto_20180814_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sala',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
