# Generated by Django 2.0.7 on 2018-08-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala', '0003_auto_20180814_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='sala',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
