# Generated by Django 2.0.7 on 2018-08-15 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala', '0004_auto_20180815_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='sala',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
