# Generated by Django 2.0.7 on 2018-08-15 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0005_auto_20180815_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
